# This file was generated by GoReleaser. DO NOT EDIT.
class Cgit < Formula
  desc "cgit is a tiny tool for Chinese developers."
  homepage "https://github.com/linuxsuren/cgit"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/LinuxSuRen/cgit/releases/download/v0.0.3/cgit-darwin-amd64.tar.gz"
    sha256 "3adb75daec6a3f7aab8597ff0c4bbaf9cb27fba32d5d4b1f75166dc6b30b05fb"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/LinuxSuRen/cgit/releases/download/v0.0.3/cgit-linux-amd64.tar.gz"
    sha256 "6e344d56b9e4899eb2e32e99588f45e0f2b8297fa5c1c191784c80ae14d8a03e"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/LinuxSuRen/cgit/releases/download/v0.0.3/cgit-linux-arm64.tar.gz"
    sha256 "c3cdeda39c727e33cfb28a024b15e38810fd8da09913e9e7acb965ae90bdcd35"
  end

  depends_on "vim" => :optional
  depends_on "bash-completion" => :optional

  def install
    bin.install name

    prefix.install_metafiles
  end

  test do
    version_output = shell_output("#{bin}/cgit version")
    assert_match version.to_s, version_output
  end
end
